/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ders02_Lab.Ornek3;

/**
 *
 * @author anizam
 */
public class frm_checkbox extends javax.swing.JFrame {

    /**
     * Creates new form frm_checkbox
     */
    public frm_checkbox() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        chxb_bir = new javax.swing.JCheckBox();
        chxb_iki = new javax.swing.JCheckBox();
        chxb_uc = new javax.swing.JCheckBox();
        lbl_goster = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        chxb_bir.setText("jCheckBox1");
        chxb_bir.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chxb_birItemStateChanged(evt);
            }
        });

        chxb_iki.setText("jCheckBox2");
        chxb_iki.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chxb_ikiItemStateChanged(evt);
            }
        });

        chxb_uc.setText("jCheckBox3");
        chxb_uc.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chxb_ucItemStateChanged(evt);
            }
        });

        lbl_goster.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(chxb_uc)
                    .addComponent(chxb_iki)
                    .addComponent(chxb_bir))
                .addGap(71, 71, 71)
                .addComponent(lbl_goster, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(128, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(chxb_bir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(chxb_iki)
                        .addGap(18, 18, 18)
                        .addComponent(chxb_uc))
                    .addComponent(lbl_goster, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(136, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void kontrol()
    {
      int say = 0;
        if (chxb_bir.isSelected()) {
            say++;
        }
        if (chxb_iki.isSelected()) {
            say++;
        }
        if (chxb_uc.isSelected()) {
            say++;
        }
        lbl_goster.setText(say + "");
    }
    private void chxb_birItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chxb_birItemStateChanged
        // TODO add your handling code here:
      kontrol();

    }//GEN-LAST:event_chxb_birItemStateChanged

    private void chxb_ikiItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chxb_ikiItemStateChanged
        // TODO add your handling code here:
        kontrol();
    }//GEN-LAST:event_chxb_ikiItemStateChanged

    private void chxb_ucItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chxb_ucItemStateChanged
        // TODO add your handling code here:
         kontrol();
    }//GEN-LAST:event_chxb_ucItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_checkbox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_checkbox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_checkbox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_checkbox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_checkbox().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox chxb_bir;
    private javax.swing.JCheckBox chxb_iki;
    private javax.swing.JCheckBox chxb_uc;
    private javax.swing.JLabel lbl_goster;
    // End of variables declaration//GEN-END:variables
}
