/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ders06Lab;

import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author anizam
 */
public class Soru1 extends javax.swing.JFrame {

    /**
     * Creates new form Soru1
     */
    DefaultTableModel mdl = new DefaultTableModel();

    public Soru1() {
        initComponents();
        
        mdl.setColumnIdentifiers(new Object[]{"Personel", "Maas"});
        mdl.addRow(new Object[]{"Ahmet AK", 2000});
        mdl.addRow(new Object[]{"Mehmet KARA", 3000});
        mdl.addRow(new Object[]{"Ay?e YE??L", 5000});
        tbl_tablo.setModel(mdl);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_tablo = new javax.swing.JTable();
        txt_sonuc = new javax.swing.JTextField();
        btn_toplam = new javax.swing.JButton();
        btn_buyuk = new javax.swing.JButton();
        btn_zamyap = new javax.swing.JButton();
        btn_duzelt1 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tbl_tablo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbl_tablo);

        btn_toplam.setText("Toplam");
        btn_toplam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_toplamActionPerformed(evt);
            }
        });

        btn_buyuk.setText("En Büyük");
        btn_buyuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buyukActionPerformed(evt);
            }
        });

        btn_zamyap.setText("Zam Yap");
        btn_zamyap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_zamyapActionPerformed(evt);
            }
        });

        btn_duzelt1.setText("Duzelt1");
        btn_duzelt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_duzelt1ActionPerformed(evt);
            }
        });

        jButton1.setText("Duzelt2");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(btn_buyuk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_toplam, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btn_zamyap))
                        .addGap(77, 77, 77)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_sonuc)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_duzelt1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(57, 57, 57))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_toplam)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_buyuk)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_zamyap)
                        .addContainerGap(33, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txt_sonuc, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_duzelt1)
                            .addComponent(jButton1))
                        .addGap(41, 41, 41))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_toplamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_toplamActionPerformed
        // TODO add your handling code here:
        int toplam=0;
        for (int i = 0; i < mdl.getRowCount(); i++) {
            toplam+= Integer.parseInt(mdl.getValueAt(i, 1).toString());
        }
        
        txt_sonuc.setText(toplam+"");
        
    }//GEN-LAST:event_btn_toplamActionPerformed

    private void btn_buyukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buyukActionPerformed
        // TODO add your handling code here:
        int enbuyuk=0;
        String isim="";
        for (int i = 0; i < mdl.getRowCount(); i++) {
            int maas=Integer.parseInt(mdl.getValueAt(i, 1).toString());
            if(maas > enbuyuk)
            {
                enbuyuk=maas;
                isim= mdl.getValueAt(i, 0).toString();
            }
            else if(maas == enbuyuk)
            {
                isim+=" "+ mdl.getValueAt(i, 0).toString();
            }
           
        }
        
        txt_sonuc.setText(isim+" "+ enbuyuk);
    }//GEN-LAST:event_btn_buyukActionPerformed

    private void btn_zamyapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_zamyapActionPerformed
        // TODO add your handling code here:
        for (int i = 0; i < mdl.getRowCount(); i++) {
            int maas=Integer.parseInt(mdl.getValueAt(i, 1).toString());
            if(maas < 2200)
            {
                mdl.setValueAt(maas+1000, i, 1);
            }
        }
        
    }//GEN-LAST:event_btn_zamyapActionPerformed

    private void btn_duzelt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_duzelt1ActionPerformed
        // TODO add your handling code here:
         for (int i = 0; i < mdl.getRowCount(); i++) {
            String maas=mdl.getValueAt(i, 1).toString();
            String ymaas="";
             for (int j = 0; j < maas.length(); j++) {
                 char c=maas.charAt(j);
                 if(Character.isDigit(c))
                 {
                     ymaas+=c;
                 }
             }
             mdl.setValueAt(ymaas, i, 1);
        }
        
    }//GEN-LAST:event_btn_duzelt1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String desen="[\\d]";
        Pattern p= Pattern.compile(desen);
        Matcher m;
                
         for (int i = 0; i < mdl.getRowCount(); i++) {
            String maas=mdl.getValueAt(i, 1).toString();
            String ymaas="";
            m= p.matcher(maas);
            while(m.find())
            {
                ymaas+= m.group();
            }
            mdl.setValueAt(ymaas, i, 1);
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Soru1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Soru1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Soru1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Soru1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Soru1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_buyuk;
    private javax.swing.JButton btn_duzelt1;
    private javax.swing.JButton btn_toplam;
    private javax.swing.JButton btn_zamyap;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_tablo;
    private javax.swing.JTextField txt_sonuc;
    // End of variables declaration//GEN-END:variables
}
