/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ders01_Lab;

/**
 *
 * @author anizam
 */
public class Ornek10 extends javax.swing.JFrame {

    /**
     * Creates new form Ornek10
     */
    public Ornek10() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_bir = new javax.swing.JButton();
        btn_iki = new javax.swing.JButton();
        btn_uc = new javax.swing.JButton();
        lbl_mesaj = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn_bir.setText("1");
        btn_bir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_birActionPerformed(evt);
            }
        });

        btn_iki.setText("2");
        btn_iki.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ikiActionPerformed(evt);
            }
        });

        btn_uc.setText("3");
        btn_uc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ucActionPerformed(evt);
            }
        });

        lbl_mesaj.setBackground(new java.awt.Color(0, 255, 102));
        lbl_mesaj.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbl_mesaj.setForeground(new java.awt.Color(0, 204, 204));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_uc)
                    .addComponent(btn_iki)
                    .addComponent(btn_bir))
                .addGap(37, 37, 37)
                .addComponent(lbl_mesaj, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(167, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(btn_bir)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_iki)
                    .addComponent(lbl_mesaj, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btn_uc)
                .addContainerGap(145, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    int tiklalanbuton = 0;
    private void btn_birActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_birActionPerformed
        // TODO add your handling code here:
        if (tiklalanbuton != 0) {
            if (tiklalanbuton == 3) {
                lbl_mesaj.setText("Do?ru");
            } else {
                lbl_mesaj.setText("Yanl??");
            }
        }
        tiklalanbuton = 1;
    }//GEN-LAST:event_btn_birActionPerformed

    private void btn_ikiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ikiActionPerformed
        // TODO add your handling code here:
        if (tiklalanbuton != 0) {
            if (tiklalanbuton == 1) {
                lbl_mesaj.setText("Do?ru");
            } else {
                lbl_mesaj.setText("Yanl??");
            }
        }
        tiklalanbuton = 2;

    }//GEN-LAST:event_btn_ikiActionPerformed

    private void btn_ucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ucActionPerformed
        // TODO add your handling code here:
         if (tiklalanbuton != 0) {
            if (tiklalanbuton == 2) {
                lbl_mesaj.setText("Do?ru");
            } else {
                lbl_mesaj.setText("Yanl??");
            }
        }
        tiklalanbuton = 3;
    }//GEN-LAST:event_btn_ucActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ornek10.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ornek10.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ornek10.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ornek10.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ornek10().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_bir;
    private javax.swing.JButton btn_iki;
    private javax.swing.JButton btn_uc;
    private javax.swing.JLabel lbl_mesaj;
    // End of variables declaration//GEN-END:variables
}
